# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "cmkr_for_beginners"

[target.hello_world]
type = "executable"
sources = ["src/main.cpp"]
compile-features = ["cxx_std_20"]

cmake-before = """
message(STATUS "DXSDK_DIR at: ${DXSDK_DIR}")
link_directories(${DXSDK_DIR}\\\\Lib\\\\x64)
include_directories(${DXSDK_DIR}\\\\Include)
"""
