name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2019]
    env:
      BUILD_TYPE: Release
    steps:
          
    - name: Install DXSDK
      run: |
        git clone https://github.com/gmh5225/DX9-lib
        
    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
        
